MODEL:
  META_ARCHITECTURE: "Detr"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 100
    NUM_CLASSES: 5
    DEEP_SUPERVISION: True
  ROI_HEADS:
    NUM_CLASSES: 5
  ROI_BOX_HEAD:
    TMP_VARIABLE: ''
DATASETS:
  TEST: ("KITTI_test",)
  TRAIN: ("KITTI_train","KITTI_val")
  CATEGORY_NAMES:
  - pedestrian
  - car
  - cyclist
  - van
  - truck
  IGNORE_NAMES:
  - dontcare
  - ignore
  - void
  MAX_DEPTH: 100000000.0
  MIN_HEIGHT_THRES: 0.05
  MODAL_2D_BOXES: false
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TRUNCATION_THRES: 0.75
  TRUNC_2D_BOXES: true
  VISIBILITY_THRES: 0.25
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (369600,)
  MAX_ITER: 554400
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 1280)
  FORMAT: "RGB"
OUTPUT_DIR: output/detr_kitti
SEED: 10
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  BALANCE_DATASETS: false
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
VERSION: 2